---
title: "Results_A_Figure_2_HTML"

output: rmarkdown::github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Setup

```{r, message=FALSE, warning=FALSE}
if (!require(pacman)) {
  install.packages("pacman")
  require(pacman)
}

p_load(readr, dplyr, broom, ggplot2, GGally, lme4, sjPlot, viridis)

```

# Data loading


```{r, message=FALSE, warning=FALSE}

### This is the datasheet used for the growth curves, with scaffold size over time as measured by the Matlab script.

df <- read_csv("Data/Growth_Data_All_Angles_REVISIONS_FIG_2.csv")


### This is the main datasheet, here used just for the boxplot in Fig. 2b.

df_final <- read.csv("Data/Main_DataSheet_Scaffolding_PNAS_2020_FINAL2.csv", header=TRUE, na.strings=c("","NA"))


df <- df %>%
  mutate(Scaled_Ants = ceiling(normalized_area * Scale_Factor))

df_ratio <- df_final %>%
  mutate(Total_Traf = Mu * 600) %>%
  mutate(Proportion_Stopped = A / Total_Traf)
  
```

---

# Scaffold growth over time

Plots for all the experimental observations of scaffold size over time, grouped by angle. Color scale indicates rate of prey tranport (in prey-carrying ants/s). These are compiled into Figure 2A.

## 90 degrees

```{r}

# df_90 <- df  %>%
#   filter(angle == "90") %>%
#   filter(second %% 2 == 0)

df_90 <- df  %>%
  filter(angle == "90")

ggplot(df_90, aes(second, Scaled_Ants)) +
  geom_point(aes(colour = Prey), alpha = .34, size = 1.17) +
  #geom_smooth() +
  theme_bw(base_size = 25) +
  ylim(0, 109) +
  theme(aspect.ratio=1) +
  theme(panel.grid.minor = element_blank()) +
  theme(panel.grid.major = element_line(size = .5)) +
  xlab("Time (s)") + ylab("Scaffold size (ants)") +
  #theme(axis.title.x=element_blank()) +
  #theme(axis.title.y=element_blank()) +
  #theme(legend.position = "none") +
  scale_color_viridis(limits = c(0,0.5), begin = 0.05) +
  #scale_color_viridis() +
  labs(colour = "Rate of prey \ntransport \n(ants/s)\n") +
  theme(text = element_text(size=12))
#ggsave("90curves_REVISED.pdf")


```

## 80 degrees

```{r}

df_80 <- df  %>%
  filter(angle == "80")

ggplot(df_80, aes(second, Scaled_Ants)) +
  geom_point(aes(colour = Prey), alpha = .34, size = 1.17) +
  #geom_smooth() +
  theme_bw(base_size = 25) +
  ylim(0, 108) +
  theme( aspect.ratio=1) +
  theme(panel.grid.minor = element_blank()) +
  theme(panel.grid.major = element_line(size = .5)) +
  xlab("Time (s)") + ylab("Scaffold size (ants)") +
  #theme(axis.title.x=element_blank()) +
  #theme(axis.title.y=element_blank()) +
  #theme(legend.position = "none") +
  #scale_color_viridis() +
  scale_color_viridis(limits = c(0,0.5), begin = 0.08) +
  labs(colour = "Rate of prey \ntransport \n(ants/s)\n") +
  theme(text = element_text(size=12))
#ggsave("80curves_REVISED.pdf")
#ggsave("80curves_loess.pdf")
```

## 70 degrees

```{r}

df_70 <- df  %>%
  filter(angle == "70") 

ggplot(df_70, aes(second, Scaled_Ants)) +
  geom_point(aes(colour = Prey), alpha = .34, size = 1.17) +
  #geom_smooth() +
  theme_bw(base_size = 25) +
  ylim(0, 108) +
  theme(aspect.ratio=1) +
  theme(panel.grid.minor = element_blank()) +
  theme(panel.grid.major = element_line(size = .5)) +
  xlab("Time (s)") + ylab("Scaffold size (ants)") +
  #theme(axis.title.x=element_blank()) +
  #theme(axis.title.y=element_blank()) +
  #theme(legend.position = "none") +
  scale_color_viridis(limits = c(0,0.5), begin = 0.08) +
  labs(colour = "Rate of prey \ntransport \n(ants/s)\n") +
  theme(text = element_text(size=12))
#ggsave("70curves_REVISED.pdf")
#ggsave("70curves_loess.pdf")

```

## 60 degrees

```{r}

df_60 <- df  %>%
  filter(angle == "60") 

ggplot(df_60, aes(second, Scaled_Ants)) +
  geom_point(aes(colour = Prey), alpha = .34, size = 1.17) +
  #geom_smooth() +
  theme_bw(base_size = 25) +
  ylim(0, 108) +
  theme(aspect.ratio=1) +
  theme(panel.grid.minor = element_blank()) +
  theme(panel.grid.major = element_line(size = .5)) +
  xlab("Time (s)") + ylab("Scaffold size (ants)") +
  #theme(axis.title.x=element_blank()) +
  #theme(axis.title.y=element_blank()) +
  #theme(legend.position = "none") +
  scale_color_viridis(limits = c(0,0.5), begin = 0.08) +
  labs(colour = "Rate of prey \ntransport \n(ants/s)\n") +
  theme(text = element_text(size=12))
#ggsave("60curves_REVISED.pdf")
#ggsave("60curves_loess.pdf")
```

## 50 degrees

```{r}

df_50 <- df  %>%
  filter(angle == "50") 

ggplot(df_50, aes(second, Scaled_Ants)) +
  geom_point(aes(colour = Prey), alpha = .33, size = 1.16) +
  #geom_smooth() +
  theme_bw(base_size = 25) +
  ylim(0, 108) +
  theme(aspect.ratio=1) +
  theme(panel.grid.minor = element_blank()) +
  theme(panel.grid.major = element_line(size = .5)) +
  xlab("Time (s)") + ylab("Scaffold size (ants)") +
  #theme(axis.title.x=element_blank()) +
  #theme(axis.title.y=element_blank()) +
  #theme(legend.position = "none") +
  scale_color_viridis(limits = c(0,0.5), begin = 0.08) +
  labs(colour = "Rate of prey \ntransport \n(ants/s)\n") +
  theme(text = element_text(size=12))
#ggsave("50curves_REVISED.pdf")
#ggsave("50curves_loess.pdf")
```

## 40 degrees

```{r}

df_40 <- df  %>%
  filter(angle == "40") 

ggplot(df_40, aes(second, Scaled_Ants)) +
  geom_point(aes(colour = Prey), alpha = .33, size = 1.16) +
  #geom_smooth() +
  theme_bw(base_size = 25) +
  ylim(0, 108) +
  theme(aspect.ratio=1) +
  theme(panel.grid.minor = element_blank()) +
  theme(panel.grid.major = element_line(size = .5)) +
  xlab("Time (s)") + ylab("Scaffold size (ants)") +
  #theme(axis.title.x=element_blank()) +
  #theme(axis.title.y=element_blank()) +
  #theme(legend.position = "none") +
  scale_color_viridis(limits = c(0,0.5), begin = 0.08) +
  labs(colour = "Rate of prey \ntransport \n(ants/s)\n") +
  theme(text = element_text(size=12))
#ggsave("40curves_REVISED.pdf")
#ggsave("40curves_loess.pdf")
```

## 30 degrees

```{r}

df_30 <- df  %>%
  filter(angle == "30")

ggplot(df_30, aes(second, Scaled_Ants)) +
  geom_point(aes(colour = Prey), alpha = .33, size = 1.16) +
  #geom_smooth() +
  theme_bw(base_size = 25) +
  ylim(0, 108) +
  theme(aspect.ratio=1) +
  theme(panel.grid.minor = element_blank()) +
  theme(panel.grid.major = element_line(size = .5)) +
  xlab("Time (s)") + ylab("Scaffold size (ants)") +
  #theme(axis.title.x=element_blank()) +
  #theme(axis.title.y=element_blank()) +
  #theme(legend.position = "none") +
  scale_color_viridis(limits = c(0,0.5), begin = 0.08) +
  labs(colour = "Rate of prey \ntransport \n(ants/s)\n") +
  theme(text = element_text(size=12))
#ggsave("30curves_REVISED.pdf")
#ggsave("30curves_loess.pdf")
```

## 20 degrees

```{r}

df_20 <- df  %>%
  filter(angle == "20") 

ggplot(df_20, aes(second, Scaled_Ants)) +
  geom_point(aes(colour = Prey), alpha = .33, size = 1.16) +
  #geom_smooth() +
  theme_bw(base_size = 25) +
  ylim(0, 108) +
  theme(aspect.ratio=1) +
  theme(panel.grid.minor = element_blank()) +
  theme(panel.grid.major = element_line(size = .5)) +
  xlab("Time (s)") + ylab("Scaffold size (ants)") +
  #theme(axis.title.x=element_blank()) +
  #theme(axis.title.y=element_blank()) +
  #theme(legend.position = "none") +
  scale_color_viridis(limits = c(0,0.5), begin = 0.08) +
  labs(colour = "Rate of prey \ntransport \n(ants/s)\n") +
  theme(text = element_text(size=12))
#ggsave("20curves_REVISED.pdf")
#ggsave("20curves_loess.pdf")
```
# Final scaffold size per angle

## Summary boxplot, Fig. 2b.

```{r}

### Plotting for Fig. 2b
ggplot(df_final, aes(x=factor(Angle), y=A)) + 
  geom_boxplot(fill="gray", width = 0.6, alpha=0.4, outlier.shape=NA) +
  theme_bw(base_size = 18) +
  theme(aspect.ratio=.65, legend.position = "none", axis.text=element_text(size=12),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.y = element_blank(),
        panel.grid.major.y = element_line( size=.1, color="black"),
        axis.title = element_text(size=14,face="bold"),
        plot.title = element_text(size=18, face="bold", hjust = 0.5)) +
  geom_jitter(size = 1.3, color = "red", width = 0.18, alpha=.45) +
  xlab("\nSurface angle") + ylab("Scaffold size (ants)")
#ggsave("boxplot_RESUBMISSION.pdf")

```
